<?php
/**
 * Created by PhpStorm.
 * User: dimasik
 * Date: 26.11.18
 * Time: 5.46
 */

namespace Test\Db\Model\ResourceModel;


class Employee extends \Magento\Eav\Model\Entity\AbstractEntity
{
    public function getEntityType()
    {
        if(empty($this->_type)) {
            $this->setType(10);
        }
        return parent::getEntityType(); // TODO: Change the autogenerated stub
    }

    public function getConfig()
    {
        return $this->_eavConfig;
    }
}