<?php
/**
 * Created by PhpStorm.
 * User: dimasik
 * Date: 16.12.18
 * Time: 18.06
 */

namespace Test\RequestFlow\Controller\Adminhtml\Index;

use Magento\Backend\App\Action as BackendAction;

class Index extends BackendAction
{
    public function execute()
    {
       echo 1111;
       die;
    }

    public function _isAllowed()
    {
       $T = $this->_authorization->isAllowed('Test_RequestFlow::test_backend'); // TODO: Change the autogenerated stub
        return $T;
    }
}